language: c
install:
- sudo apt-get install gradle
script: ./configure --prefix="$PWD/root" && make
after_success: if [[ -n ${TRAVIS_TAG} ]]; then make zip dist_name=${TRAVIS_TAG}; fi
deploy:
  provider: releases
  api_key:
    secure: T5KBo6hIAMHJoak4qFI3ORuIupt9L/alzQoZK6ssoKXfiYyWrr+m2r2E7MKpGDG9cqiUDk6HI/R75kh8At4JrToOfTC2OUBhV6QSq2S457WzS3eQvsRkxoc2gWQYO5Y4ccTEuR6QB9a/pxQGLC/+WuRMo7nhmmnfErsdr0b++t0=
  file: tmp/${TRAVIS_TAG}.zip
  on:
    all_branches: true
    tags: true
